#!/usr/bin/env python3
"""Send reverie email using the protophysics mail API.

Requires environment variables (or .env file):
  EMAIL_SERVER      - e.g. http://192.168.4.41:5003
  EMAIL_ADDRESS     - sender email address
  EMAIL_PASSWORD    - sender password
  EMAIL_TO          - recipient email address (optional, defaults to EMAIL_ADDRESS)
"""
import argparse
import os
import requests
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import date


def get_auth_token(email_server: str, email: str, password: str) -> str:
    """Get auth token from mail server."""
    response = requests.post(
        f"{email_server}/auth/login",
        json={"email": email, "password": password}
    )
    response.raise_for_status()
    return response.json()["token"]


def send_reverie_email(
    target_date: date,
    summary_md: str,
    reflections: str,
    next_day_ideas: str,
    email_server: str,
    email_from: str,
    email_to: str,
    email_password: str,
) -> dict:
    """Send reverie via email."""
    token = get_auth_token(email_server, email_from, email_password)

    subject = f"Nightly Reverie - {target_date}"

    # Build HTML body
    html_body = f"""<!DOCTYPE html>
<html>
<head><title>Nightly Reverie - {target_date}</title></head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
<h1 style="color: #2c3e50;">🌙 Nightly Reverie - {target_date}</h1>

<h2 style="color: #34495e;">Summary</h2>
<div style="background: #f8f9fa; padding: 15px; border-radius: 8px;">
{summary_md.replace('## Summary', '').strip()}
</div>

<h2 style="color: #34495e;">Reflections</h2>
<div style="background: #e8f5e9; padding: 15px; border-radius: 8px;">
{reflections.replace('## Reflections', '').strip()}
</div>

<h2 style="color: #34495e;">Next Day Ideas</h2>
<div style="background: #fff3e0; padding: 15px; border-radius: 8px;">
{next_day_ideas.replace('## Next Day Ideas', '').strip()}
</div>

<hr style="margin-top: 30px; border: none; border-top: 1px solid #ddd;">
<p style="color: #666; font-size: 12px;">Generated by Clawbie - Your AI Assistant</p>
</body>
</html>"""

    # Create MIME message
    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From'] = email_from
    msg['To'] = email_to

    html_part = MIMEText(html_body, 'html', 'utf-8')
    msg.attach(html_part)

    # Send via MIME endpoint
    response = requests.post(
        f"{email_server}/api/emails/mime",
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
        json={"to": email_to, "mime_content": msg.as_string()}
    )

    if response.status_code == 201:
        print(f"Email sent to {email_to}")
        return response.json()
    else:
        raise Exception(f"Failed to send email: {response.status_code} - {response.text}")


def main():
    import sys
    sys.path.insert(0, str(__file__.rsplit("/", 3)[0]))
    import os
    from pathlib import Path

    # Load .env from clawbie repo
    env_path = Path(__file__).parent.parent.parent.parent / ".env"
    if env_path.exists():
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if "=" in line and not line.startswith("#"):
                    key, value = line.split("=", 1)
                    value = value.strip().strip('"')
                    if key not in os.environ:
                        os.environ[key] = value

    # Require email config
    email_server = os.environ.get("EMAIL_SERVER", "")
    email_from = os.environ.get("EMAIL_ADDRESS", "")
    email_password = os.environ.get("EMAIL_PASSWORD", "")
    email_to = os.environ.get("EMAIL_TO", email_from)
    if not email_server or not email_from or not email_password:
        raise ValueError("EMAIL_SERVER, EMAIL_ADDRESS, and EMAIL_PASSWORD must be set in environment or .env")

    parser = argparse.ArgumentParser(description="Send reverie email")
    parser.add_argument("--date", required=True, help="Date (YYYY-MM-DD)")
    args = parser.parse_args()

    # Get reverie from database
    import psycopg
    db_url = os.environ.get("DATABASE_URL")
    if not db_url:
        raise ValueError("DATABASE_URL must be set in environment or .env")
    conn = psycopg.connect(db_url)
    cursor = conn.cursor()
    cursor.execute("""
        SELECT summary_md, reflections, next_day_ideas
        FROM nightly_reverie
        WHERE date = %s
    """, (args.date,))
    row = cursor.fetchone()
    cursor.close()
    conn.close()

    if not row:
        print(f"No reverie found for {args.date}")
        return

    summary_md, reflections, next_day_ideas = row

    send_reverie_email(args.date, summary_md, reflections, next_day_ideas,
                       email_server, email_from, email_to, email_password)
    print("Done!")


if __name__ == "__main__":
    main()